Repository SWE2-2020-8/NewBank, pull requests merged in 2020-08, with the labels that each got.

#73 Added pay interest function for admins
  client/src/AccountController.java
  client/src/BankClient.java
Labels: enhancement

#75 PayInterest corrected
  newbankclient.jar
  server/src/NewBank.java
Labels: bug, enhancement

#77 Rounding to two decimals
  client/src/fxml/LoginScene.fxml
  server/src/Account.java
  server/src/NewBank.java
Labels: bug
